<?xml version="1.0"?>
<!DOCTYPE note [

<!ELEMENT note (to,from,heading,body+)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body ANY>
]>

<note>
	<to>Tove</to>
	<from>Jani</from>
	<heading>Reminder</heading>
	<body>
		<to>Tove</to>
	</body>
</note>